# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import time
import paho.mqtt.client as paho
from paho import mqtt
from pymodbus.client.sync import ModbusTcpClient
from pymodbus.client.sync import ModbusSerialClient
import sqlite3
import datetime
#import subprocess

#subprocess.call("modbas3.py", shell=True)

from bitarray import bitarray
import struct
from struct import *

conn = sqlite3.connect('baza.db')

c = conn.cursor()
start = 0
stop = 0
spreman = 0
smetnje = 1
tabla = 0
vrijednost = 5
aprevious = [0 for x in range(32)]

#c.execute("""CREATE TABLE testtable (
           # timestamp datetime,
           # greska text,
           # brGreske integer
           # )""")
greska = ["" for x in range(22)]
greska[0] = "Smetnje zatezanja trake"
greska[1] = "Preteze uze desno"
greska[2] = "Preteze uze lijevo"
greska[3] = "Bocno skretanje rep"
greska[4] = "Bocno skretanje pog. st."
greska[5] = "Preopt. Bimetal m1"
greska[6] = "Preopt. Bimetal m2"
greska[7] = "Preg. Os m1"
greska[8] = "Pregar. os m2"
greska[9] = "Grij.Rez.Red m1"
greska[10] = "Grij. Nam m1"
greska[11] = "Grij. lez. m2"
greska[12] = "Grij. Nam m2"
greska[13] = "sf6 gas m1"
greska[14] = "SF6 gas m2"
greska[15] = "Zapunj. kosa"
greska[16] = "Not pogon"
greska[17] = "Not kljuc"
greska[18] = "Proklizavanje"
greska[19] = "Krajnji vrata M1"
greska[20] = "Krajnji vrata M2"
greska[21] = "Greska kocnice sig"

def insertVaribleIntoTable(timestamp, greska, brGreske):
   
    global c
    global conn

    sqlite_insert_with_param = """INSERT INTO testtable(
                    timestamp, greska,
                    brGreske)
                    VALUES(?,?,?);"""

    data_tuple = (timestamp, greska, brGreske)
    c.execute(sqlite_insert_with_param, data_tuple)
    conn.commit()

    


#client1 = ModbusTcpClient("192.168.137.11")
#client1 = ModbusSerialClient(method = 'rtu', port = "COM3")

#print(client1.connect())
# setting callbacks for different events to see if it works, print the message etc.
def on_connect(client, userdata, flags, rc, properties=None):
    print("CONNACK received with code %s." % rc)

# with this callback you can see if your publish was successful
def on_publish(client, userdata, mid, properties=None):
    print("mid: " + str(mid))

# print which topic was subscribed to
def on_subscribe(client, userdata, mid, granted_qos, properties=None):
    print("Subscribed: " + str(mid) + " " + str(granted_qos))

# print message, useful for checking if it was successful

def on_message(client, userdata, msg):
    print(msg.topic)
    global vrijednost
    if(msg.topic == "plc/start"):
        global start
        start = msg.payload
    if(msg.topic == "plc/stop"):
        global stop
        stop = msg.payload
    if(msg.topic == "plc/spreman"):
        global spreman
        spreman = msg.payload
    if(msg.topic == "plc/smetnje"):
        global smetnje
        smetnje = msg.payload
        
    if(msg.topic == "plc/tabla"):
        global tabla
        tabla = msg.payload
    

# using MQTT version 5 here, for 3.1.1: MQTTv311, 3.1: MQTTv31
# userdata is user defined data of any type, updated by user_data_set()
# client_id is the given name of the client
client = paho.Client(client_id="", userdata=None, protocol=paho.MQTTv5)
client.on_connect = on_connect

# enable TLS for secure connection
client.tls_set(tls_version=mqtt.client.ssl.PROTOCOL_TLS)
# set username and password
client.username_pw_set("nemanja1", "Pijanista123!")
# connect to HiveMQ Cloud on port 8883 (default for MQTT)
client.connect("264182fcba8747a8ab21160de2312abb.s2.eu.hivemq.cloud", 8883)


# setting callbacks, use separate functions like above for better visibility
client.on_subscribe = on_subscribe
client.on_message = on_message
client.on_publish = on_publish
client.loop_start()







class Ui_IstorijaGresaka(object):
    def setupUi(self, IstorijaGresaka):
        IstorijaGresaka.setObjectName("IstorijaGresaka")
        IstorijaGresaka.resize(1046, 1002)
        self.buttonBox = QtWidgets.QDialogButtonBox(IstorijaGresaka)
        self.buttonBox.setGeometry(QtCore.QRect(670, 560, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tableView = QtWidgets.QTableView(IstorijaGresaka)
        self.tableView.setGeometry(QtCore.QRect(30, 10, 531, 441))
        self.tableView.setObjectName("tableView")
        self.tableView_2 = QtWidgets.QTableView(IstorijaGresaka)
        self.tableView_2.setGeometry(QtCore.QRect(580, 10, 451, 441))
        self.tableView_2.setAutoFillBackground(True)
        self.tableView_2.setSortingEnabled(True)
        self.tableView_2.setObjectName("tableView_2")
        self.lineEdit = QtWidgets.QLineEdit(IstorijaGresaka)
        self.lineEdit.setGeometry(QtCore.QRect(860, 470, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(IstorijaGresaka)
        self.commandLinkButton.setGeometry(QtCore.QRect(930, 470, 91, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.comboBox = QtWidgets.QComboBox(IstorijaGresaka)
        self.comboBox.setGeometry(QtCore.QRect(640, 470, 151, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(IstorijaGresaka)
        self.pushButton.setGeometry(QtCore.QRect(50, 470, 141, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(IstorijaGresaka)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 470, 141, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(IstorijaGresaka)
        self.pushButton_3.setGeometry(QtCore.QRect(550, 850, 111, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableView_3 = QtWidgets.QTableView(IstorijaGresaka)
        self.tableView_3.setGeometry(QtCore.QRect(50, 540, 451, 411))
        self.tableView_3.setObjectName("tableView_3")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(IstorijaGresaka)
        self.dateTimeEdit.setGeometry(QtCore.QRect(550, 610, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(16)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(IstorijaGresaka)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(550, 670, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(16)
        self.dateTimeEdit_2.setFont(font)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")

        self.retranslateUi(IstorijaGresaka)
        self.buttonBox.accepted.connect(IstorijaGresaka.accept)
        self.buttonBox.rejected.connect(IstorijaGresaka.reject)
        QtCore.QMetaObject.connectSlotsByName(IstorijaGresaka)

    def retranslateUi(self, IstorijaGresaka):
        _translate = QtCore.QCoreApplication.translate
        IstorijaGresaka.setWindowTitle(_translate("IstorijaGresaka", "Dialog"))
        self.commandLinkButton.setText(_translate("IstorijaGresaka", "Potvrdi"))
        self.comboBox.setItemText(0, _translate("IstorijaGresaka", "Smetnje zatezanja trake"))
        self.comboBox.setItemText(1, _translate("IstorijaGresaka", "Preteze uze desno"))
        self.comboBox.setItemText(2, _translate("IstorijaGresaka", "Preteze uze lijevo"))
        self.comboBox.setItemText(3, _translate("IstorijaGresaka", "Bocno skretanje rep"))
        self.comboBox.setItemText(4, _translate("IstorijaGresaka", "Bocno skretanje pog.st."))
        self.comboBox.setItemText(5, _translate("IstorijaGresaka", "preopt.Bimetal M1"))
        self.comboBox.setItemText(6, _translate("IstorijaGresaka", "Preopt.Bimetal M2"))
        self.comboBox.setItemText(7, _translate("IstorijaGresaka", "Preg. Os M1"))
        self.comboBox.setItemText(8, _translate("IstorijaGresaka", "Grij. rez red M1"))
        self.comboBox.setItemText(9, _translate("IstorijaGresaka", "Grij.Nam M1"))
        self.comboBox.setItemText(10, _translate("IstorijaGresaka", "Grj.lez M2"))
        self.comboBox.setItemText(11, _translate("IstorijaGresaka", "Grij.Nam M2"))
        self.comboBox.setItemText(12, _translate("IstorijaGresaka", "SF6 gas M1"))
        self.comboBox.setItemText(13, _translate("IstorijaGresaka", "SF6 gas M2"))
        self.comboBox.setItemText(14, _translate("IstorijaGresaka", "Zapunj.Kosa"))
        self.comboBox.setItemText(15, _translate("IstorijaGresaka", "Not pogon"))
        self.comboBox.setItemText(16, _translate("IstorijaGresaka", "Not kljuc"))
        self.comboBox.setItemText(17, _translate("IstorijaGresaka", "Proklizavanja"))
        self.comboBox.setItemText(18, _translate("IstorijaGresaka", "Krajnji vrata M1"))
        self.comboBox.setItemText(19, _translate("IstorijaGresaka", "Krajnji vrata M2"))
        self.comboBox.setItemText(20, _translate("IstorijaGresaka", "Greska kocnice sig"))
        self.pushButton.setText(_translate("IstorijaGresaka", "Obrisi BAZU"))
        self.pushButton_2.setText(_translate("IstorijaGresaka", "Osvjezi BAZU"))
        self.pushButton_3.setText(_translate("IstorijaGresaka", "Potvrdi vrijeme"))

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1501, 749)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 131, 51))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 100, 111, 51))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(260, 100, 101, 51))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(360, 100, 121, 51))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(480, 100, 141, 51))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(620, 100, 121, 51))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(730, 100, 141, 51))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(870, 100, 141, 51))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 150, 131, 51))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(150, 150, 121, 51))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(270, 150, 101, 51))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(370, 150, 101, 51))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(470, 150, 101, 51))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(570, 150, 81, 51))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(650, 150, 81, 51))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(730, 150, 101, 51))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(830, 150, 91, 51))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(920, 150, 91, 51))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(20, 200, 101, 51))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(120, 200, 101, 51))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(220, 200, 111, 51))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(330, 200, 121, 51))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(450, 200, 111, 51))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(540, 200, 91, 51))
        self.label_26.setObjectName("label_26")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 330, 141, 91))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 330, 141, 91))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 330, 141, 91))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(470, 330, 141, 91))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1020, 110, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 260, 131, 41))
        self.label_2.setObjectName("label_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(970, 330, 221, 101))
        self.pushButton_5.clicked.connect(lambda: button_5_clicked(self.pushButton_5))

        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(1220, 10, 221, 211))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(630, 20, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 30, 113, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(420, 30, 81, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(50, 0, 101, 21))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(300, 0, 49, 16))
        self.label_29.setObjectName("label_29")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1501, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        def button_5_clicked(PushButton):

            self.w = QtWidgets.QDialog()
            ui = Ui_IstorijaGresaka()
            ui.setupUi(self.w)
            self.w.show()
        def changelabelcolor():
            
            client.loop_start()
            client.subscribe("plc/tabla", qos=1)
            
            global tabla
            a = bitarray('0' * 32, endian='little')
            v=int(tabla)

            for k in range(32):
                a[k] = 0
                #z = bin(tabla)
                
                
                
                mask = (1 << k)
                if(tabla & mask):
                   a[k] = tabla.bits[0]
                else:
                   a[k]=0

            print(vrijednost)
            
            z = struct.unpack("<L", a)[0]
            print(z)
            vrijeme = datetime.datetime.now()
            global aprevious
            for it in range(22):
                if(a[it]==0 and a[it]!=aprevious[it]):
                    global greska
                    insertVaribleIntoTable(vrijeme, greska[it], it)

                       
            
            aprevious = a     
      
            if(a[0] == 0):
                self.label_3.setStyleSheet("background-color: red")
            else:
                self.label_3.setStyleSheet("background-color: green")
            if(a[1] == 0):
                self.label_4.setStyleSheet("background-color: red")
            else:
                self.label_4.setStyleSheet("background-color: green")
            if(a[2] == 0):
                self.label_5.setStyleSheet("background-color: red")
            else:
                self.label_5.setStyleSheet("background-color: green")
            if(a[3] == 0):
                self.label_6.setStyleSheet("background-color: red")
            else:
                self.label_6.setStyleSheet("background-color: green")
            if(a[4] == 0):
                self.label_7.setStyleSheet("background-color: red")
            else:
                self.label_7.setStyleSheet("background-color: green")
            if(a[5] == 0):
                self.label_8.setStyleSheet("background-color: red")
            else:
                self.label_8.setStyleSheet("background-color: green")
            if(a[6] == 0):
                self.label_9.setStyleSheet("background-color: red")
            else:
                self.label_9.setStyleSheet("background-color: green")
            if(a[7] == 0):
                self.label_10.setStyleSheet("background-color: red")
            else:
                self.label_10.setStyleSheet("background-color: green")
            if(a[8] == 0):
                self.label_11.setStyleSheet("background-color: red")
            else:
                self.label_11.setStyleSheet("background-color: green")
            if(a[9] == 0):
                self.label_12.setStyleSheet("background-color: red")
            else:
                self.label_12.setStyleSheet("background-color: green")
            if(a[10] == 0):
                self.label_13.setStyleSheet("background-color: red")
            else:
                self.label_13.setStyleSheet("background-color: green")
            if(a[11] == 0):
                self.label_14.setStyleSheet("background-color: red")
            else:
                self.label_14.setStyleSheet("background-color: green")
            if(a[12] == 0):
                self.label_15.setStyleSheet("background-color: red")
            else:
                self.label_15.setStyleSheet("background-color: green")
            if(a[13] == 0):
                self.label_16.setStyleSheet("background-color: red")
            else:
                self.label_16.setStyleSheet("background-color: green")
            if(a[14] == 0):
                self.label_17.setStyleSheet("background-color: red")
            else:
                self.label_17.setStyleSheet("background-color: green")
            if(a[15] == 0):
                self.label_18.setStyleSheet("background-color: red")
            else:
                self.label_18.setStyleSheet("background-color: green")
            if(a[16] == 0):
                self.label_19.setStyleSheet("background-color: red")
            else:
                self.label_19.setStyleSheet("background-color: green")
            if(a[17] == 0):
                self.label_20.setStyleSheet("background-color: red")
            else:
                self.label_20.setStyleSheet("background-color: green")
            if(a[18] == 0):
                self.label_21.setStyleSheet("background-color: red")
            else:
                self.label_21.setStyleSheet("background-color: green")
            if(a[19] == 0):
                self.label_22.setStyleSheet("background-color: red")
            else:
                self.label_22.setStyleSheet("background-color: green")
            if(a[20] == 0):
                self.label_23.setStyleSheet("background-color: red")
            else:
                self.label_23.setStyleSheet("background-color: green")
            if(a[21] == 0):
                self.label_24.setStyleSheet("background-color: red")
            else:
                self.label_24.setStyleSheet("background-color: green")
            if(a[22] == 0):
                self.label_25.setStyleSheet("background-color: red")
            else:
                self.label_25.setStyleSheet("background-color: green")
            if(a[23] == 0):
                self.label_26.setStyleSheet("background-color: red")
            else:
                self.label_26.setStyleSheet("background-color: green")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(changelabelcolor)
        self.timer.start(4000)  
              
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Smetnje Zat trake"))
        self.label_4.setText(_translate("MainWindow", "Pot. Uze Desno"))
        self.label_5.setText(_translate("MainWindow", "Pot. Uze Lijevo"))
        self.label_6.setText(_translate("MainWindow", "Bocno Skretanje Rep"))
        self.label_7.setText(_translate("MainWindow", "Bocno Skretanje Pog St"))
        self.label_8.setText(_translate("MainWindow", "Preopt. Bimetal m1"))
        self.label_9.setText(_translate("MainWindow", "Preopt. Bim. m2"))
        self.label_10.setText(_translate("MainWindow", "Preg.Os.M1"))
        self.label_11.setText(_translate("MainWindow", "Preg.Os.M2"))
        self.label_12.setText(_translate("MainWindow", "Grij.Lez.Led m1"))
        self.label_13.setText(_translate("MainWindow", "Grij.nam m1"))
        self.label_14.setText(_translate("MainWindow", "Grij.Lez.Led m2"))
        self.label_15.setText(_translate("MainWindow", "Grij.nam.m2"))
        self.label_16.setText(_translate("MainWindow", "Sf6. gas m1"))
        self.label_17.setText(_translate("MainWindow", "Sf6. gas m2"))
        self.label_18.setText(_translate("MainWindow", "Zapunj. kosa"))
        self.label_19.setText(_translate("MainWindow", "Not pogon"))
        self.label_20.setText(_translate("MainWindow", "Not Kljuc"))
        self.label_21.setText(_translate("MainWindow", "Proklizavanje"))
        self.label_22.setText(_translate("MainWindow", "Krajnji vrata m1"))
        self.label_23.setText(_translate("MainWindow", "Krajnji Vrata m2"))
        self.label_24.setText(_translate("MainWindow", "Greska Kocnice sig"))
        self.label_25.setText(_translate("MainWindow", "Start Kontejner"))
        self.label_26.setText(_translate("MainWindow", "Start Rukovaoc"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.pushButton_2.setText(_translate("MainWindow", "STOP"))
        self.pushButton_3.setText(_translate("MainWindow", "SPREMAN ZA RAD"))
        self.pushButton_4.setText(_translate("MainWindow", "Kvitiranje Smetnji"))
        self.label.setText(_translate("MainWindow", "Proklizavanje"))
        self.label_2.setText(_translate("MainWindow", "DataBase"))
        self.pushButton_5.setText(_translate("MainWindow", "ISTORIJA GRESAKA"))
        self.label_27.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_6.setText(_translate("MainWindow", "Konektuj"))
        self.label_28.setText(_translate("MainWindow", "IP adresa"))
        self.label_29.setText(_translate("MainWindow", "Port"))




if __name__ == "__main__":
    import sys
    client.loop_start()
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())



